### ISSUE TITLE
SPARQL editor: Better out-of-the-box experience

### ISSUE THREAD

**Issue by wouterbeek** [ClioPatria/ClioPatria#6]
Currently ClioPatria ships with three SPARQL query editors: Yasgui, Flint, and some text form. Upon default installation only the text form is present (the other 2 require additional installation steps).

For an optimal out-of-the-box experience ClioPatria should come with 1 SPARQL query editor, preferably a good and intuitive one. Since Yasgui's featureset is a superset of the other 2 I would suggest to:

  - Auto-install Yasgui packs upon ClioPatria installation/configuration.
  - Remove the Flint and text form menu items from the menu since these may confuse novice users.

**Comment by JanWielemaker** [comment]
I think I agree to remove Flint, also because the latest update is 2 years old.  Funny enough though,
many users like the good old textarea ...  For YASGUI, I suppose we must add a few lines in the
default installation guidelines to run the submodule init commands.  This cannot be part of configure
because it is not really part of the project but of the overall system.

**Comment by wouterbeek** [comment]
I agree that it makes sense to keep the text area around, also due to being less reliant on external libraries and such.

**Comment by JanWielemaker** [comment]
Changed Flint to be something you can add using `configure --with-flint` (and install the git
submodule).
