### ISSUE TITLE
SPARQL Update LOAD resourceIRI INTO GRAPH <graphIRI> not conform specification

### ISSUE THREAD

**Issue by wmelder** [ClioPatria/ClioPatria#64]
The SPARQL update HTTP API shows unexpected behaviour for [LOAD ](https://www.w3.org/TR/sparql11-update/#load) request.
The LOAD operation should get the triples from the resourceIRI and add them to the graph. Currently, the graph is cleared before the triples are added. This is explicitly not the expected behaviour: `If the destination graph already exists, then no data in that graph will be removed.`

**Comment by JanWielemaker** [comment]
Can you be a bit more specific?

**Comment by wmelder** [comment]
So, I am sending these requests to /sparql/update: 
`LOAD <http://data.rdlabs.beeldengeluid.nl/resource/program/4193880> INTO GRAPH <http://data.rdlabs.beeldengeluid.nl/tv/actualiteiten>`
`LOAD <http://data.rdlabs.beeldengeluid.nl/resource/program/4191738> INTO GRAPH <http://data.rdlabs.beeldengeluid.nl/tv/actualiteiten>`

After that, inspecting the graph shows that the graph is only sourced by the 'Source URL':
![image](https://user-images.githubusercontent.com/1220375/60710154-52ddb500-9f12-11e9-91f6-d24b070edce8.png)

**Comment by JanWielemaker** [comment]
That is because rdf_load/2 clears the graph before loading.   That makes a lot of sense as originally RDF store developers introduced graphs to keep track of the origin of triples ...  But then people started to use graphs for different things :( Added an option `multifile(+Boolean)` to allow rdf_load/2 to load multiple sources into the same graph and use that in ClioPatria.  To use this, you need to update to the git version of SWI-Prolog and update ClioPatria to the latest git version.
